/**
 * The corpus the chat assistant retrieves against.
 *
 * Generated by the import so it can never drift from the published records.
 * It is bundled into the Pages Function at build time rather than fetched at
 * runtime: it is small, it is needed on every request, and a fetch would add
 * latency to the one thing a person in a crisis is waiting on.
 *
 * Two rules are enforced here rather than in the prompt, because a prompt is a
 * request and this is a guarantee:
 *   - Organizations that have closed or left the city are excluded outright.
 *     The assistant cannot recommend what it cannot see.
 *   - Every contact detail the assistant is allowed to utter is present in
 *     these records, so the response filter has an exact allow-list.
 */
import type { Org } from '../../src/types.ts';
import { keywordsFor } from '../../src/data/synonyms.ts';

export interface CorpusOrg {
  id: string;
  name: string;
  aka: string[];
  animals: string[];
  needs: string[];
  boroughs: string[];
  zips: string[];
  citywide: boolean;
  outsideNyc: boolean;
  confidence: 'High' | 'Medium' | 'Low';
  status: Org['status'];
  statusNote: string | null;
  lastVerified: string | null;
  /** Display strings, e.g. "(718) 436-5163". */
  phones: string[];
  emails: string[];
  website: string | null;
  intake: string | null;
  hours: string | null;
  address: string | null;
  /** One line, for the prompt. Full notes stay on the organization's page. */
  summary: string;
  keywords: string;
  text: string;
}

export interface CorpusGuide {
  slug: string;
  title: string;
  summary: string;
  topics: string[];
  /** Each section of the guide, small enough to put one in a prompt. */
  chunks: Array<{ heading: string; text: string }>;
}

/** Statuses the assistant must never recommend. */
const EXCLUDED: ReadonlyArray<Org['status']> = ['retired', 'relocated'];

/**
 * A newly discovered organization is real, but nothing about it has been
 * checked. It can be browsed and filtered on the site, where the label says
 * so plainly; it is not handed to someone in a crisis as an answer. It becomes
 * eligible once a weekly check finds a working contact on its own site.
 */
function isUnverifiedDiscovery(o: Org): boolean {
  return o.check_status === 'new-unverified';
}

function firstSentences(text: string | null, max = 200): string {
  if (!text) return '';
  const clean = text.replace(/\s+/g, ' ').trim();
  if (clean.length <= max) return clean;
  const cut = clean.slice(0, max);
  const lastStop = cut.lastIndexOf('. ');
  return (lastStop > 60 ? cut.slice(0, lastStop + 1) : `${cut.trimEnd()}…`).trim();
}

export function buildOrgCorpus(orgs: Org[]): CorpusOrg[] {
  return orgs
    .filter((o) => !EXCLUDED.includes(o.status) && !isUnverifiedDiscovery(o))
    .map((o) => ({
      id: o.id,
      name: o.name,
      aka: o.aka,
      animals: o.animals,
      needs: o.needs,
      boroughs: o.boroughs,
      zips: o.zips,
      citywide: o.citywide,
      outsideNyc: o.outside_nyc,
      confidence: o.confidence,
      status: o.status,
      statusNote: o.status_note,
      lastVerified: o.last_verified,
      phones: o.phones.map((p) => p.display),
      emails: o.emails.map((e) => e.value),
      website: o.website,
      intake: o.intake_urls[0]?.url ?? null,
      hours: o.hours,
      address: o.address?.street
        ? `${o.address.street}${o.address.zip ? `, ${o.address.zip}` : ''}`
        : null,
      summary: firstSentences(o.notes),
      keywords: keywordsFor(o.animals, o.needs, o.org_types),
      text: [o.neighborhoods, o.type_raw, o.notes].filter(Boolean).join(' ').replace(/\s+/g, ' ').slice(0, 280),
    }));
}

/**
 * Split a guide into sections. Chunks stay whole: a warning and its reason
 * belong in the same piece of text, because half of "do not give food or
 * water" is worse than none of it.
 */
export function chunkGuide(markdown: string, title: string): Array<{ heading: string; text: string }> {
  const body = markdown.replace(/^---\n[\s\S]*?\n---\n/, '');
  const chunks: Array<{ heading: string; text: string }> = [];
  let heading = title;
  let buffer: string[] = [];

  const flush = () => {
    const text = buffer.join('\n').replace(/\n{3,}/g, '\n\n').trim();
    if (text) chunks.push({ heading, text: text.slice(0, 1800) });
    buffer = [];
  };

  for (const line of body.split('\n')) {
    const h = /^#{1,3}\s+(.*)$/.exec(line);
    if (h) {
      flush();
      heading = h[1]!.trim();
      continue;
    }
    buffer.push(line);
  }
  flush();
  return chunks.filter((c) => c.text.length > 40);
}
